export const SCENE_KEYS = Object.freeze({
    TEST_SCENE: 'TEST_SCENE',
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    BATTLE_SCENE: 'BATTLE_SCENE',
    TITLE_SCENE: 'TITLE_SCENE',
    OPTIONS_SCENE: 'OPTIONS_SCENE',
})