export const SCENE_KEYS = Object.freeze({
    TEST_SCENE: 'TEST_SCENE',
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    BATTLE_SCENE: 'BATTLE_SCENE',
    TITLE_SCENE: 'TITLE_SCENE',
    OPTIONS_SCENE: 'OPTIONS_SCENE',
    MAIN_GAME_SCENE: 'MAIN_GAME_SCENE',
    MONSTER_DETAILS_SCENE: 'MONSTER_DETAILS_SCENE',
    MONSTER_PARTY_SCENE: 'MONSTER_PARTY_SCENE',
    INVENTORY_SCENE: 'INVENTORY_SCENE',
})

export type SceneKeys = keyof typeof SCENE_KEYS